name: daytona runner configure
synopsis: Configure Daytona Runner
usage: daytona runner configure [flags]
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona runner - Manage the runner
